export const environment = {
    production: true,
    BASE_URL: 'https://quiz.st.stumagz.com/',
    userToken:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJlMzNjM2Q5ZGMzNTE2YjJmNjQ4OGQiLCJ1c2VybmFtZSI6InZpa2FzNiIsImZpcnN0TmFtZSI6InZpa2FzIiwibGFzdE5hbWUiOiJkdXBhdGkiLCJpc3N1ZWRUbyI6ImJsb2ciLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE1ODk1MjM2ODUsImV4cCI6MTU4OTk1NTY4NSwiaXNzIjoiYWNjb3VudHMuc3R1bWFnei5jb20iLCJqdGkiOiJGaTFaMTU4OTUyMzY4NTM5M1NvaWQifQ.7SVCJrDio7DI2rcquMq_UyIsY--4PLriS6c0BeqZFeo',
    adminToken: 'stadmin',
    adminToken1:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTczM2RjNTBmMjZiYTMwMTJhMGZkOTkiLCJmaXJzdE5hbWUiOiJidW5ueSIsImxhc3ROYW1lIjoidmlzaGFsIiwidXNlcm5hbWUiOiJidW5ueXZpc2hhbDYiLCJpc3N1ZWRUbyI6ImJsb2ciLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE1ODkyOTk2MjgsImV4cCI6MTU4OTczMTYyOCwiaXNzIjoiYWNjb3VudHMuc3R1bWFnei5jb20iLCJqdGkiOiI0QW9yMTU4OTI5OTYyODY1MUJYalkifQ.o_zoV5huuEdHced9RwgMX-IuwRUDHNfTKnz3e_Vo0eY',
};
